introduction/urls.py
from django.conf.urls import url
from introduction import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^intro/$', views.intro, name='intro'),
]

mypage/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^about/', include('introduction.urls', namespace='about')),
    url(r'^admin/', admin.site.urls),

]

urlpatterns += static('/media/', document_root=settings.MEDIA_ROOT)

introduction/models.py
from django.db import models

# Create your models here.

introduction/views.py
from django.shortcuts import render, redirect

# Create your views here.

def index(request):
    return render(request, 'introduction/index.html')

def intro(request):
    return render(request, 'introduction/index2.html')

introduction/templates/introduction/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Hello, I'm A Young</title>

<div class="page-header">
  <center><h1>Lee A Young <br><small>1997.05.09</small></h1></center>
</div>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  </head>
  <body>
<div class="row">
  <center><div class="col-xs-6 col-md-3">
    <a href="{% url 'about:intro' %}" class="thumbnail"><img src="{% static '/static/a.jpg' %}" alt="My image"/></a>
  </div></center>
</div>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  </body>
</html>

introduction/templates/introduction/index2.html
<!DOCTYPE html>
<html>
<head>

</head>
<body>
<br>
<br>
<center><font size=5>
원미고등학교를 졸업하고,<br>
현재 한양대학교 문화콘텐츠학과 재학 중!<br>
'웹'에 관심이 많고, 웹디자인이나 웹콘텐츠나 웹기획 웹 개발 등등 많은 관심을 갖고 있음!<br>
꽃다운 나이 스무살이지만 나에게 아직 꽃이 피진 않은듯함...ㅠ<br><br></font>
<br><center><img src="아영사진2.jpg" width="500"></center><br><br>
<audio src="비망록 (스물의 노래)_버즈_Buzz Effect.mp3" controls autoplay></audio><br><br><br>
<font size=4><strong>
내가 고등학생일 때...</strong></font>
<font size=3>
<ul>
<li>2013.03 ~ 2016.02 교지편집부 '헤드라인'의 부원, 부장으로서 활동
<li>2013.07 ~ 2015.06 원미고등학교 17,18대 학생회 특활부 차/부장
<li>2014.07 ~ 2015.06 부천시청소년늘픔기자단
<li>2015.03 ~ 2016.02 방송(자율)동아리 On Air 부장
</ul>
</font>
<br>
<font size=4><strong>
대학생인 현재의 나는...</strong></font>
<font size=3>
<ul>
<li>2016.03~ 한양대학교 문화콘텐츠학과 창업학회 CRACKER의 학회원
<li>2016광주웹콘텐츠페스티벌 서포터즈 'SENSEE' 활동
<li>2016.06~ 피로그래밍 5기
</ul>
</font>
<br>
<font size=4><strong>
나의 목표는...</strong></font>
<br>
<br>
<font size=3>
'학점 관리→졸업→취업'의 평범한 루트가 아닌,<br>
내가 진정하고 하고 싶어하는 것들을 배우고 실력을 쌓아서<br>
나만의 CAREER를 만드는 것!<br>
이를 위해 많은 도전을 해보고 싶다.</font>
<br>
<br>
<br>
<iframe width="560" height="315" src="https://www.youtube.com/embed/x4x542fFBis" frameborder="0" allowfullscreen></iframe>
</body>
</html>